`Assignmnet no 1`

Name: Shantanu Kaute | Roll No. 07 | PRN no. 1252090007

1.Perform the following operations using Python on suitable data sets:

Read data from different formats (like csv, xls)
Find Shape of Data
Find Missing Values
Find data type of each column
Finding out Zero's
Indexing and selecting data, sort data,
Describe attributes of data, checking data types of each column,
counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)

Important liberaries which required with dealing the data

In [ ]:
import pandas as pd
import numpy as np

 Student Data set

In [ ]:
import pandas as pd;
data = {
"Student ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
"Name": ["Shantanu", "Sai", "Jay", "Snehal", "Rahul", "Pooja", "Kunal", "Anjali", "Saurabh", "Neha"],
"Age": [18, 15, 28, 12, 20, 18, 19, 20, 19, 18],
"Gender": ["Male", "Male", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
"Department": ["CSE AI", "CSE", "CSE AI", "CSE", "IT", "CSE AI", "IT", "CSE", "CSE AI", "IT"],
"Marks": [9.1, 8.6, 8.9, 9.3, 8.2, 9.0, 8.4, 9.2, 8.7, 9.1],
"Attendance": [95, 94, 93, 92, 92, 98, 90, 91, 93, 95],
"Internship": ["Yes", "Yes", "Yes", "Yes", "No", "Yes", "No", "Yes", "Yes", "Yes"]
}
df = pd.DataFrame(data)
print(df)

   Student ID      Name  Age  Gender Department  Marks  Attendance Internship
0         101  Shantanu   18    Male     CSE AI    9.1          95        Yes
1         102       Sai   15    Male        CSE    8.6          94        Yes
2         103       Jay   28    Male     CSE AI    8.9          93        Yes
3         104    Snehal   12  Female        CSE    9.3          92        Yes
4         105     Rahul   20    Male         IT    8.2          92         No
5         106     Pooja   18  Female     CSE AI    9.0          98        Yes
6         107     Kunal   19    Male         IT    8.4          90         No
7         108    Anjali   20  Female        CSE    9.2          91        Yes
8         109   Saurabh   19    Male     CSE AI    8.7          93        Yes
9         110      Neha   18  Female         IT    9.1          95        Yes

Read data from different fromats (CSV, XLS)

In [ ]:
from google.colab import files
uploaded = files.upload()
print(uploaded)

Saving student_data.csv to student_data (2).csv

In [ ]:
dff=pd.read_csv('student_data.csv')
dff

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

Find shape of data gives rows and column

In [ ]:
df.shape

(10, 8)

Find missing value

In [ ]:
df.isnull().sum()

Student ID    0
Name          0
Age           0
Gender        0
Department    0
Marks         0
Attendance    0
Internship    0
dtype: int64

In [ ]:
df.isnull().any()

Student ID    False
Name          False
Age           False
Gender        False
Department    False
Marks         False
Attendance    False
Internship    False
dtype: bool

Finding data types

In [ ]:
df.dtypes

Student ID      int64
Name           object
Age             int64
Gender         object
Department     object
Marks         float64
Attendance      int64
Internship     object
dtype: object

**Finding out Zeros **

In [ ]:
(df==0).sum()

Student ID    0
Name          0
Age           0
Gender        0
Department    0
Marks         0
Attendance    0
Internship    0
dtype: int64

In [ ]:
(df.select_dtypes(include=np.number)==0).sum()

Student ID    0
Age           0
Marks         0
Attendance    0
dtype: int64

**Indexing ,selecting data and sorting **

In [ ]:
df['Student ID']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Student ID, dtype: int64

In [ ]:
dff[['school']]

    school
0       GP
1       GP
2       GP
3       GP
4       GP
..     ...
390     MS
391     MS
392     MS
393     MS
394     MS

[395 rows x 1 columns]

In [ ]:
dff.iloc[0:5]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
dff[dff['age']>15]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

Introduction and 10 minute

Sort Data

In [ ]:
dff.sort_values(by='age',ascending=True)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
36,GP,M,15,U,LE3,T,4,3,teacher,services,...,5,4,3,1,1,4,2,15,16,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
306,GP,M,20,U,GT3,A,3,2,services,other,...,5,5,3,1,1,5,0,17,18,18
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
247,GP,M,22,U,GT3,T,3,1,services,services,...,5,4,5,5,5,1,16,6,8,8

Descibe Attributes & check Data types

In [ ]:
dff.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [ ]:
df.describe(include='all')

,Student ID,Name,Age,Gender,Department,Marks,Attendance,Internship
count,10.00000,10,10.000000,10,10,10.000000,10.000000,10
unique,NaN,10,NaN,2,3,NaN,NaN,2
top,NaN,Shantanu,NaN,Male,CSE AI,NaN,NaN,Yes
freq,NaN,1,NaN,6,4,NaN,NaN,8
mean,105.50000,NaN,18.700000,NaN,NaN,8.850000,93.300000,NaN
std,3.02765,NaN,4.083844,NaN,NaN,0.362859,2.311805,NaN
min,101.00000,NaN,12.000000,NaN,NaN,8.200000,90.000000,NaN
25%,103.25000,NaN,18.000000,NaN,NaN,8.625000,92.000000,NaN
50%,105.50000,NaN,18.500000,NaN,NaN,8.950000,93.000000,NaN
75%,107.75000,NaN,19.750000,NaN,NaN,9.100000,94.750000,NaN
max,110.00000,NaN,28.000000,NaN,NaN,9.300000,98.000000,NaN

Check data types again

In [ ]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

**Count unique value , format & Data types Conversion **

In [ ]:
df.nunique()

Student ID    10
Name          10
Age            6
Gender         2
Department     3
Marks          9
Attendance     7
Internship     2
dtype: int64

In [ ]:
dff['age'].value_counts()

age
16    104
17     98
18     82
15     82
19     24
20      3
22      1
21      1
Name: count, dtype: int64

In [ ]:
dff.applymap(type)

/tmp/ipython-input-255471094.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dff.applymap(type)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
1,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
2,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
3,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
4,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
391,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
392,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
393,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>
394,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,...,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>

**Converting variable data types **

In [ ]:
dff['age']=dff['age'].astype(float)

In [ ]:
dff['age']=dff['age'].astype(int)

In [ ]:
dff['school']=dff['school'].astype('category')

 Import as follows:

In [ ]:
import numpy as np
import pandas as pd

Object Creation

See the Intro to data structures section.
Creating a Series by passing a list of values, letting pandas create a default integer index:

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a DataFrame by passing a NumPy array, with a datetime index using date_range() and labeled columns:

In [ ]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.631567 -0.703992  1.221846 -1.062098
2013-01-02 -1.023470 -0.171616 -0.521982 -1.247480
2013-01-03 -0.431877 -0.468739  1.359356  1.159070
2013-01-04  0.199685  0.588314 -1.563385 -0.442762
2013-01-05 -0.666667  0.281978 -0.712405 -0.779234
2013-01-06  0.395033 -0.735824 -0.691703 -1.460358

Creating a DataFrame by passing a dictionary of objects that can be converted into a series-like structure:

In [ ]:
df2 = pd.DataFrame(
{
"A": 1.0,
"B": pd.Timestamp("20130102"),
"C": pd.Series(1, index=list(range(4)), dtype="float32"),
"D": np.array([3] * 4, dtype="int32"),
"E": pd.Categorical(["test", "train", "test", "train"]),
"F": "foo",
}
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

The columns of the resulting DataFrame have different dtypes :

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

Viewing data

See the Basics section.

Use DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame respectively:

In [ ]:
df.head()

                   A         B         C         D
2013-01-01  0.631567 -0.703992  1.221846 -1.062098
2013-01-02 -1.023470 -0.171616 -0.521982 -1.247480
2013-01-03 -0.431877 -0.468739  1.359356  1.159070
2013-01-04  0.199685  0.588314 -1.563385 -0.442762
2013-01-05 -0.666667  0.281978 -0.712405 -0.779234

In [ ]:
df.tail(3)

                   A         B         C         D
2013-01-04  0.199685  0.588314 -1.563385 -0.442762
2013-01-05 -0.666667  0.281978 -0.712405 -0.779234
2013-01-06  0.395033 -0.735824 -0.691703 -1.460358

Display the DataFrame.index or DataFrame.columns :

In [ ]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

DataFrame.to_numpy() gives a NumPy representation of the underlying data. Note that this can be an expensive operation when
your DataFrame has columns with different data types, which comes down to a fundamental difference between pandas and NumPy:
NumPy arrays have one dtype for the entire array, while pandas DataFrames have one dtype per column. When you call
DataFrame.to_numpy() , pandas will find the NumPy dtype that can hold all of the dtypes in the DataFrame. This may end up being
object , which requires casting every value to a Python object.
For df , our DataFrame of all floating-point values, and DataFrame.to_numpy() is fast and doesn’t require copying data:

In [ ]:
df.to_numpy()

array([[ 0.6315673 , -0.70399225,  1.22184566, -1.06209791],
       [-1.02347001, -0.17161556, -0.52198223, -1.24748024],
       [-0.43187709, -0.46873852,  1.35935557,  1.15907038],
       [ 0.19968519,  0.58831352, -1.56338514, -0.44276209],
       [-0.66666668,  0.28197822, -0.71240529, -0.7792336 ],
       [ 0.39503314, -0.73582405, -0.69170341, -1.46035752]])

For df2 , the DataFrame with multiple dtypes, DataFrame.to_numpy() is relatively expensive:

In [ ]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

NOTE: DataFrame.to_numpy() does not include the index or column labels in the output

describe() shows a quick statistic summary of your data:

In [ ]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.149288 -0.201646 -0.151379 -0.638810
std    0.654146  0.541824  1.175234  0.950276
min   -1.023470 -0.735824 -1.563385 -1.460358
25%   -0.607969 -0.645179 -0.707230 -1.201135
50%   -0.116096 -0.320177 -0.606843 -0.920666
75%    0.346196  0.168580  0.785889 -0.526880
max    0.631567  0.588314  1.359356  1.159070

Transposing your data:

In [ ]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.631567   -1.023470   -0.431877    0.199685   -0.666667    0.395033
B   -0.703992   -0.171616   -0.468739    0.588314    0.281978   -0.735824
C    1.221846   -0.521982    1.359356   -1.563385   -0.712405   -0.691703
D   -1.062098   -1.247480    1.159070   -0.442762   -0.779234   -1.460358

In [ ]:
df.sort_values(by='B')

                   A         B         C         D
2013-01-06  0.395033 -0.735824 -0.691703 -1.460358
2013-01-01  0.631567 -0.703992  1.221846 -1.062098
2013-01-03 -0.431877 -0.468739  1.359356  1.159070
2013-01-02 -1.023470 -0.171616 -0.521982 -1.247480
2013-01-05 -0.666667  0.281978 -0.712405 -0.779234
2013-01-04  0.199685  0.588314 -1.563385 -0.442762

Getting

Selecting a single column, which yields a Series , equivalent to df.A :

In [ ]:
df["A"]

2013-01-01    0.631567
2013-01-02   -1.023470
2013-01-03   -0.431877
2013-01-04    0.199685
2013-01-05   -0.666667
2013-01-06    0.395033
Freq: D, Name: A, dtype: float64

Selecting via [] ( __getitem__ ), which slices the rows:

In [ ]:
df[0:3]

                   A         B         C         D
2013-01-01  0.631567 -0.703992  1.221846 -1.062098
2013-01-02 -1.023470 -0.171616 -0.521982 -1.247480
2013-01-03 -0.431877 -0.468739  1.359356  1.159070

In [ ]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -1.023470 -0.171616 -0.521982 -1.247480
2013-01-03 -0.431877 -0.468739  1.359356  1.159070
2013-01-04  0.199685  0.588314 -1.563385 -0.442762

Selection by label

Selecting on a multi-axis by label:

In [ ]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.631567 -0.703992
2013-01-02 -1.023470 -0.171616
2013-01-03 -0.431877 -0.468739
2013-01-04  0.199685  0.588314
2013-01-05 -0.666667  0.281978
2013-01-06  0.395033 -0.735824

Showing label slicing, both endpoints are included:

In [ ]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02 -1.023470 -0.171616
2013-01-03 -0.431877 -0.468739
2013-01-04  0.199685  0.588314

Selection by position

See more in Selection by Position using DataFrame.iloc() or DataFrame.at() .
Select via the position of the passed integers:

In [ ]:
df.iloc[3]

A    0.199685
B    0.588314
C   -1.563385
D   -0.442762
Name: 2013-01-04 00:00:00, dtype: float64

By integer slices, acting similar to NumPy/Python:

In [ ]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  0.199685  0.588314
2013-01-05 -0.666667  0.281978

For slicing rows explicitly:

In [ ]:
df.iloc[1:3, :]

                   A         B         C        D
2013-01-02 -1.023470 -0.171616 -0.521982 -1.24748
2013-01-03 -0.431877 -0.468739  1.359356  1.15907

For slicing columns explicitly:

In [ ]:
df.iloc[:, 1:3]

                   B         C
2013-01-01 -0.703992  1.221846
2013-01-02 -0.171616 -0.521982
2013-01-03 -0.468739  1.359356
2013-01-04  0.588314 -1.563385
2013-01-05  0.281978 -0.712405
2013-01-06 -0.735824 -0.691703

Boolean indexing

Using a single column’s values to select data:

In [ ]:
df[df["A"] > 0]

                   A         B         C         D
2013-01-01  0.631567 -0.703992  1.221846 -1.062098
2013-01-04  0.199685  0.588314 -1.563385 -0.442762
2013-01-06  0.395033 -0.735824 -0.691703 -1.460358

Selecting values from a DataFrame where a boolean condition is met:

In [ ]:
df[df > 0]

                   A         B         C        D
2013-01-01  0.631567       NaN  1.221846      NaN
2013-01-02       NaN       NaN       NaN      NaN
2013-01-03       NaN       NaN  1.359356  1.15907
2013-01-04  0.199685  0.588314       NaN      NaN
2013-01-05       NaN  0.281978       NaN      NaN
2013-01-06  0.395033       NaN       NaN      NaN